---
title: "CASE Workshop Example"
author: "Ursula Tooley"
date: "May 17, 2016"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='asis')
```


##Data prep
```{r}
library(haven)
atlas<-read_sav("data/ATLAS.sav")
atlas$use0 <- factor(atlas$use0, 
                     levels=c(0,1), 
                     labels=c("no", "yes"))
atlas$intervention <- factor(atlas$intervention, 
                             levels=c(0,1), 
                             labels=c("no", "yes"))


```


##Running model
```{r}
model1 <- lm(STSE1~intervention*STSE0, data=atlas, na.action=na.exclude)
plot(model1)



```
##Summarizing the model


```{r}
library(pander)
model.sum <- summary(model1)
pander(model.sum)
```

##Plotting
```{r}
library(ggplot2)
ggplot(atlas,aes(x=STSE0, y=STSE1)) +
  geom_point(alpha=.3)
#alpha makes points transparent, goes from 1 to 0
ggplot(atlas,aes(x=STSE0, y=STSE1, color=intervention)) +
  geom_point(alpha=.3)
#to plot a factor, get 2 scatterplots instead of one
ggplot(atlas,aes(x=STSE0, y=STSE1, color=intervention)) +
  geom_point(alpha=.3)+
  facet_wrap(~intervention)
atlas$intervention <- factor(atlas$intervention, levels=c("yes", "no"), labels=c("intervention", "control"))
ggplot(atlas,aes(x=STSE0, y=STSE1, color=intervention)) +
  geom_point(alpha=.3)+
  facet_wrap(~intervention)

#use predict to run exactly the line that your model predicts
model1 <- lm(STSE1~intervention*STSE0, data=atlas, na.action=na.exclude)
atlas$pred <- predict(model1,atlas)
ggplot(atlas,aes(x=STSE0, y=STSE1, color=intervention)) +
  geom_point(alpha=.3)


```



